# These are supported funding model platforms

github:[frank-mendez]
patreon: frankmendez
open_collective: frank-mendez
ko_fi: frank-mendez
tidelift: frank-mendez
community_bridge: frank-mendez
liberapay: frank-mendez
issuehunt: frank-mendez
otechie: frank-mendez
lfx_crowdfunding: frank-mendez
custom: 
